// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
//  protoc-gen-go v1.23.0
//  protoc        v3.12.4
// source: events.proto

package pb

import (
    reflect "reflect"
    sync "sync"

    proto "github.com/golang/protobuf/proto"
    protoreflect "google.golang.org/protobuf/reflect/protoreflect"
    protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
    // Verify that this generated code is sufficiently up-to-date.
    _ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
    // Verify that runtime/protoimpl is sufficiently up-to-date.
    _ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type StartedEvent struct {
    state         protoimpl.MessageState
    sizeCache     protoimpl.SizeCache
    unknownFields protoimpl.UnknownFields

    DeviceId   *DeviceID  `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
    Timestamp  *Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
    Annotation string     `protobuf:"bytes,3,opt,name=annotation,proto3" json:"annotation,omitempty"`
}

func (x *StartedEvent) Reset() {
    *x = StartedEvent{}
    if protoimpl.UnsafeEnabled {
        mi := &file_events_proto_msgTypes[0]
        ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
        ms.StoreMessageInfo(mi)
    }
}

func (x *StartedEvent) String() string {
    return protoimpl.X.MessageStringOf(x)
}

func (*StartedEvent) ProtoMessage() {}

func (x *StartedEvent) ProtoReflect() protoreflect.Message {
    mi := &file_events_proto_msgTypes[0]
    if protoimpl.UnsafeEnabled && x != nil {
        ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
        if ms.LoadMessageInfo() == nil {
            ms.StoreMessageInfo(mi)
        }
        return ms
    }
    return mi.MessageOf(x)
}

// Deprecated: Use StartedEvent.ProtoReflect.Descriptor instead.
func (*StartedEvent) Descriptor() ([]byte, []int) {
    return file_events_proto_rawDescGZIP(), []int{0}
}

func (x *StartedEvent) GetDeviceId() *DeviceID {
    if x != nil {
        return x.DeviceId
    }
    return nil
}

func (x *StartedEvent) GetTimestamp() *Timestamp {
    if x != nil {
        return x.Timestamp
    }
    return nil
}

func (x *StartedEvent) GetAnnotation() string {
    if x != nil {
        return x.Annotation
    }
    return ""
}

type StoppedEvent struct {
    state         protoimpl.MessageState
    sizeCache     protoimpl.SizeCache
    unknownFields protoimpl.UnknownFields

    DeviceId   *DeviceID  `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
    Timestamp  *Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
    Annotation string     `protobuf:"bytes,3,opt,name=annotation,proto3" json:"annotation,omitempty"`
}

func (x *StoppedEvent) Reset() {
    *x = StoppedEvent{}
    if protoimpl.UnsafeEnabled {
        mi := &file_events_proto_msgTypes[1]
        ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
        ms.StoreMessageInfo(mi)
    }
}

func (x *StoppedEvent) String() string {
    return protoimpl.X.MessageStringOf(x)
}

func (*StoppedEvent) ProtoMessage() {}

func (x *StoppedEvent) ProtoReflect() protoreflect.Message {
    mi := &file_events_proto_msgTypes[1]
    if protoimpl.UnsafeEnabled && x != nil {
        ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
        if ms.LoadMessageInfo() == nil {
            ms.StoreMessageInfo(mi)
        }
        return ms
    }
    return mi.MessageOf(x)
}

// Deprecated: Use StoppedEvent.ProtoReflect.Descriptor instead.
func (*StoppedEvent) Descriptor() ([]byte, []int) {
    return file_events_proto_rawDescGZIP(), []int{1}
}

func (x *StoppedEvent) GetDeviceId() *DeviceID {
    if x != nil {
        return x.DeviceId
    }
    return nil
}

func (x *StoppedEvent) GetTimestamp() *Timestamp {
    if x != nil {
        return x.Timestamp
    }
    return nil
}

func (x *StoppedEvent) GetAnnotation() string {
    if x != nil {
        return x.Annotation
    }
    return ""
}

type DatapointAcquiredEvent struct {
    state         protoimpl.MessageState
    sizeCache     protoimpl.SizeCache
    unknownFields protoimpl.UnknownFields

    DeviceId  *DeviceID    `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
    Timestamp *Timestamp   `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
    Data      []*Datapoint `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *DatapointAcquiredEvent) Reset() {
    *x = DatapointAcquiredEvent{}
    if protoimpl.UnsafeEnabled {
        mi := &file_events_proto_msgTypes[2]
        ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
        ms.StoreMessageInfo(mi)
    }
}

func (x *DatapointAcquiredEvent) String() string {
    return protoimpl.X.MessageStringOf(x)
}

func (*DatapointAcquiredEvent) ProtoMessage() {}

func (x *DatapointAcquiredEvent) ProtoReflect() protoreflect.Message {
    mi := &file_events_proto_msgTypes[2]
    if protoimpl.UnsafeEnabled && x != nil {
        ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
        if ms.LoadMessageInfo() == nil {
            ms.StoreMessageInfo(mi)
        }
        return ms
    }
    return mi.MessageOf(x)
}

// Deprecated: Use DatapointAcquiredEvent.ProtoReflect.Descriptor instead.
func (*DatapointAcquiredEvent) Descriptor() ([]byte, []int) {
    return file_events_proto_rawDescGZIP(), []int{2}
}

func (x *DatapointAcquiredEvent) GetDeviceId() *DeviceID {
    if x != nil {
        return x.DeviceId
    }
    return nil
}

func (x *DatapointAcquiredEvent) GetTimestamp() *Timestamp {
    if x != nil {
        return x.Timestamp
    }
    return nil
}

func (x *DatapointAcquiredEvent) GetData() []*Datapoint {
    if x != nil {
        return x.Data
    }
    return nil
}

type Datapoint struct {
    state         protoimpl.MessageState
    sizeCache     protoimpl.SizeCache
    unknownFields protoimpl.UnknownFields

    Ch1 int32 `protobuf:"zigzag32,1,opt,name=ch1,proto3" json:"ch1,omitempty"`
    Ch2 int32 `protobuf:"zigzag32,2,opt,name=ch2,proto3" json:"ch2,omitempty"`
    Pps int32 `protobuf:"zigzag32,3,opt,name=pps,proto3" json:"pps,omitempty"`
}

func (x *Datapoint) Reset() {
    *x = Datapoint{}
    if protoimpl.UnsafeEnabled {
        mi := &file_events_proto_msgTypes[3]
        ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
        ms.StoreMessageInfo(mi)
    }
}

func (x *Datapoint) String() string {
    return protoimpl.X.MessageStringOf(x)
}

func (*Datapoint) ProtoMessage() {}

func (x *Datapoint) ProtoReflect() protoreflect.Message {
    mi := &file_events_proto_msgTypes[3]
    if protoimpl.UnsafeEnabled && x != nil {
        ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
        if ms.LoadMessageInfo() == nil {
            ms.StoreMessageInfo(mi)
        }
        return ms
    }
    return mi.MessageOf(x)
}

// Deprecated: Use Datapoint.ProtoReflect.Descriptor instead.
func (*Datapoint) Descriptor() ([]byte, []int) {
    return file_events_proto_rawDescGZIP(), []int{3}
}

func (x *Datapoint) GetCh1() int32 {
    if x != nil {
        return x.Ch1
    }
    return 0
}

func (x *Datapoint) GetCh2() int32 {
    if x != nil {
        return x.Ch2
    }
    return 0
}

func (x *Datapoint) GetPps() int32 {
    if x != nil {
        return x.Pps
    }
    return 0
}

type DeviceID struct {
    state         protoimpl.MessageState
    sizeCache     protoimpl.SizeCache
    unknownFields protoimpl.UnknownFields

    Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
}

func (x *DeviceID) Reset() {
    *x = DeviceID{}
    if protoimpl.UnsafeEnabled {
        mi := &file_events_proto_msgTypes[4]
        ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
        ms.StoreMessageInfo(mi)
    }
}

func (x *DeviceID) String() string {
    return protoimpl.X.MessageStringOf(x)
}

func (*DeviceID) ProtoMessage() {}

func (x *DeviceID) ProtoReflect() protoreflect.Message {
    mi := &file_events_proto_msgTypes[4]
    if protoimpl.UnsafeEnabled && x != nil {
        ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
        if ms.LoadMessageInfo() == nil {
            ms.StoreMessageInfo(mi)
        }
        return ms
    }
    return mi.MessageOf(x)
}

// Deprecated: Use DeviceID.ProtoReflect.Descriptor instead.
func (*DeviceID) Descriptor() ([]byte, []int) {
    return file_events_proto_rawDescGZIP(), []int{4}
}

func (x *DeviceID) GetUuid() string {
    if x != nil {
        return x.Uuid
    }
    return ""
}

type Timestamp struct {
    state         protoimpl.MessageState
    sizeCache     protoimpl.SizeCache
    unknownFields protoimpl.UnknownFields

    Seconds     int64 `protobuf:"varint,1,opt,name=seconds,proto3" json:"seconds,omitempty"`
    Nanoseconds int64 `protobuf:"varint,2,opt,name=nanoseconds,proto3" json:"nanoseconds,omitempty"`
}

func (x *Timestamp) Reset() {
    *x = Timestamp{}
    if protoimpl.UnsafeEnabled {
        mi := &file_events_proto_msgTypes[5]
        ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
        ms.StoreMessageInfo(mi)
    }
}

func (x *Timestamp) String() string {
    return protoimpl.X.MessageStringOf(x)
}

func (*Timestamp) ProtoMessage() {}

func (x *Timestamp) ProtoReflect() protoreflect.Message {
    mi := &file_events_proto_msgTypes[5]
    if protoimpl.UnsafeEnabled && x != nil {
        ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
        if ms.LoadMessageInfo() == nil {
            ms.StoreMessageInfo(mi)
        }
        return ms
    }
    return mi.MessageOf(x)
}

// Deprecated: Use Timestamp.ProtoReflect.Descriptor instead.
func (*Timestamp) Descriptor() ([]byte, []int) {
    return file_events_proto_rawDescGZIP(), []int{5}
}

func (x *Timestamp) GetSeconds() int64 {
    if x != nil {
        return x.Seconds
    }
    return 0
}

func (x *Timestamp) GetNanoseconds() int64 {
    if x != nil {
        return x.Nanoseconds
    }
    return 0
}

var File_events_proto protoreflect.FileDescriptor

var file_events_proto_rawDesc = []byte{
    0x0a, 0x0c, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05,
    0x64, 0x76, 0x72, 0x61, 0x73, 0x22, 0x8c, 0x01, 0x0a, 0x0c, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65,
    0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x2c, 0x0a, 0x09, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65,
    0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x64, 0x76, 0x72, 0x61,
    0x73, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x44, 0x52, 0x08, 0x64, 0x65, 0x76, 0x69,
    0x63, 0x65, 0x49, 0x64, 0x12, 0x2e, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
    0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x64, 0x76, 0x72, 0x61, 0x73, 0x2e,
    0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73,
    0x74, 0x61, 0x6d, 0x70, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69,
    0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61,
    0x74, 0x69, 0x6f, 0x6e, 0x22, 0x8c, 0x01, 0x0a, 0x0c, 0x53, 0x74, 0x6f, 0x70, 0x70, 0x65, 0x64,
    0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x2c, 0x0a, 0x09, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f,
    0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x64, 0x76, 0x72, 0x61, 0x73,
    0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x44, 0x52, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63,
    0x65, 0x49, 0x64, 0x12, 0x2e, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
    0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x64, 0x76, 0x72, 0x61, 0x73, 0x2e, 0x54,
    0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
    0x61, 0x6d, 0x70, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f,
    0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74,
    0x69, 0x6f, 0x6e, 0x22, 0x9c, 0x01, 0x0a, 0x16, 0x44, 0x61, 0x74, 0x61, 0x70, 0x6f, 0x69, 0x6e,
    0x74, 0x41, 0x63, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x2c,
    0x0a, 0x09, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
    0x0b, 0x32, 0x0f, 0x2e, 0x64, 0x76, 0x72, 0x61, 0x73, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65,
    0x49, 0x44, 0x52, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x2e, 0x0a, 0x09,
    0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
    0x10, 0x2e, 0x64, 0x76, 0x72, 0x61, 0x73, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
    0x70, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x24, 0x0a, 0x04,
    0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x64, 0x76, 0x72,
    0x61, 0x73, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x04, 0x64, 0x61,
    0x74, 0x61, 0x22, 0x41, 0x0a, 0x09, 0x44, 0x61, 0x74, 0x61, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12,
    0x10, 0x0a, 0x03, 0x63, 0x68, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x11, 0x52, 0x03, 0x63, 0x68,
    0x31, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x68, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x11, 0x52, 0x03,
    0x63, 0x68, 0x32, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x70, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x11,
    0x52, 0x03, 0x70, 0x70, 0x73, 0x22, 0x1e, 0x0a, 0x08, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49,
    0x44, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
    0x04, 0x75, 0x75, 0x69, 0x64, 0x22, 0x47, 0x0a, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
    0x6d, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18, 0x01, 0x20,
    0x01, 0x28, 0x03, 0x52, 0x07, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x12, 0x20, 0x0a, 0x0b,
    0x6e, 0x61, 0x6e, 0x6f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
    0x03, 0x52, 0x0b, 0x6e, 0x61, 0x6e, 0x6f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x62, 0x06,
    0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
    file_events_proto_rawDescOnce sync.Once
    file_events_proto_rawDescData = file_events_proto_rawDesc
)

func file_events_proto_rawDescGZIP() []byte {
    file_events_proto_rawDescOnce.Do(func() {
        file_events_proto_rawDescData = protoimpl.X.CompressGZIP(file_events_proto_rawDescData)
    })
    return file_events_proto_rawDescData
}

var file_events_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_events_proto_goTypes = []interface{}{
    (*StartedEvent)(nil),           // 0: dvras.StartedEvent
    (*StoppedEvent)(nil),           // 1: dvras.StoppedEvent
    (*DatapointAcquiredEvent)(nil), // 2: dvras.DatapointAcquiredEvent
    (*Datapoint)(nil),              // 3: dvras.Datapoint
    (*DeviceID)(nil),               // 4: dvras.DeviceID
    (*Timestamp)(nil),              // 5: dvras.Timestamp
}
var file_events_proto_depIdxs = []int32{
    4, // 0: dvras.StartedEvent.device_id:type_name -> dvras.DeviceID
    5, // 1: dvras.StartedEvent.timestamp:type_name -> dvras.Timestamp
    4, // 2: dvras.StoppedEvent.device_id:type_name -> dvras.DeviceID
    5, // 3: dvras.StoppedEvent.timestamp:type_name -> dvras.Timestamp
    4, // 4: dvras.DatapointAcquiredEvent.device_id:type_name -> dvras.DeviceID
    5, // 5: dvras.DatapointAcquiredEvent.timestamp:type_name -> dvras.Timestamp
    3, // 6: dvras.DatapointAcquiredEvent.data:type_name -> dvras.Datapoint
    7, // [7:7] is the sub-list for method output_type
    7, // [7:7] is the sub-list for method input_type
    7, // [7:7] is the sub-list for extension type_name
    7, // [7:7] is the sub-list for extension extendee
    0, // [0:7] is the sub-list for field type_name
}

func init() { file_events_proto_init() }
func file_events_proto_init() {
    if File_events_proto != nil {
        return
    }
    if !protoimpl.UnsafeEnabled {
        file_events_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
            switch v := v.(*StartedEvent); i {
            case 0:
                return &v.state
            case 1:
                return &v.sizeCache
            case 2:
                return &v.unknownFields
            default:
                return nil
            }
        }
        file_events_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
            switch v := v.(*StoppedEvent); i {
            case 0:
                return &v.state
            case 1:
                return &v.sizeCache
            case 2:
                return &v.unknownFields
            default:
                return nil
            }
        }
        file_events_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
            switch v := v.(*DatapointAcquiredEvent); i {
            case 0:
                return &v.state
            case 1:
                return &v.sizeCache
            case 2:
                return &v.unknownFields
            default:
                return nil
            }
        }
        file_events_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
            switch v := v.(*Datapoint); i {
            case 0:
                return &v.state
            case 1:
                return &v.sizeCache
            case 2:
                return &v.unknownFields
            default:
                return nil
            }
        }
        file_events_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
            switch v := v.(*DeviceID); i {
            case 0:
                return &v.state
            case 1:
                return &v.sizeCache
            case 2:
                return &v.unknownFields
            default:
                return nil
            }
        }
        file_events_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
            switch v := v.(*Timestamp); i {
            case 0:
                return &v.state
            case 1:
                return &v.sizeCache
            case 2:
                return &v.unknownFields
            default:
                return nil
            }
        }
    }
    type x struct{}
    out := protoimpl.TypeBuilder{
        File: protoimpl.DescBuilder{
            GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
            RawDescriptor: file_events_proto_rawDesc,
            NumEnums:      0,
            NumMessages:   6,
            NumExtensions: 0,
            NumServices:   0,
        },
        GoTypes:           file_events_proto_goTypes,
        DependencyIndexes: file_events_proto_depIdxs,
        MessageInfos:      file_events_proto_msgTypes,
    }.Build()
    File_events_proto = out.File
    file_events_proto_rawDesc = nil
    file_events_proto_goTypes = nil
    file_events_proto_depIdxs = nil
}
